global:
  resolve_timeout: 2m
templates:
#模板文件
  - "./template/wechat.tmpl"
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'wechat'
  routes:
    - receiver: 'wechat'
      continue: true
      group_wait: 10s
      match:
        level: '4'
receivers:
- name: 'wechat'
  wechat_configs:
  #企业id
  - corp_id: ${WECOM_ID}
  #要发送信息的部门id
    to_party: ${WECOM_PARTY_ID}
    #创建应用的id
    agent_id: ${WECOM_APP_ID}
    #Secret密钥，在应用id下面点击查看，登录手机企业微信查看
    api_secret: ${WECOM_API_SECRET}
    send_resolved: true