server.name: kibana
server.host: "0.0.0.0"
elasticsearch.hosts: [ "http://${ES_LINK}:${ES_PORT}" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
elasticsearch.username: "${ELASTIC_USER}"
elasticsearch.password: "${ELASTIC_PASSWORD}"
i18n.locale: zh-CN
