http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://${ES_LINK}:${ES_PORT}" ]
xpack.monitoring.elasticsearch.username: "${ELASTIC_USER}"
xpack.monitoring.elasticsearch.password: "${ELASTIC_PASSWORD}"
